#!/usr/bin/env bash

export PATH=/bin:/usr/local/bin:$PATH

cd /app

echo "-|| Setting base URL"
bin/magento config:set web/unsecure/base_url $MAGENTO_URL
bin/magento config:set web/secure/base_url $MAGENTO_URL